[application]

[bundle]
name = "TDARS Toolkit"
identifier = "uk.hpkns"
publisher = "Hpkns"
icon = [
    "icons/icon.png",
    "icons/icon.ico",
    "icons/icon.icns",
]
category = "Utility"
short_description = "Tools for TDARS"
long_description = "A collection of tools and utilities for the Telford and District Amateur Radio Society"

[web.app]

# HTML title tag content
title = "TDARS Toolkit"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
