name: Rust Checks

on:
  pull_request:

jobs:
  check:
    name: Check ${{ matrix.checks.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        checks:
          - name: Code (with extra features)
            command: check --locked
          - name: Code (without extra features)
            command: check --locked --no-default-features -F desktop
          - name: Formatting
            component: rustfmt
            command: fmt --check
          - name: Clippy Suggestions
            component: clippy
            command: clippy --all-features

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: ${{ matrix.checks.component }}

      - name: Checking ${{ matrix.checks.name }}
        run: cargo ${{ matrix.checks.command }}
